version: '3.0'
services:
  redisdb:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    container_name: redisdb-container
    #command: ["redis-server", "--bind", "redisdb", "--port", "6379"]
    volumes:
      - ./redis-data:/data # Named volumes. redis-data is named volume & /data/db is path inside container

  urlshortnerservice:
    build:
      context: ./api
    depends_on:
      - redisdb
    ports:
      - "3001:3001"
    restart: always
    container_name: url-shortner-container
    image: url-shortner-service
    volumes:
      - ./api:./api #host directory:container directory

volumes:
  redis-data:
  #driver: local
