apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: url-shortner
spec:
  ports:
  - port: {{ .Values.deployment.port }}
    targetPort: {{ .Values.deployment.containerPort }}
    name: http
  selector:
    app: url-shortner
    version: v1